import { supabase } from './supabase'

const SEED_RECIPES = [
  {
    id: 'seed-1',
    name: 'Avocado Toast with Soft-Boiled Eggs',
    category: 'breakfast',
    servings: 2,
    prepTime: 10,
    cookTime: 8,
    notes: 'Use sourdough or thick-cut bread for best results. A pinch of chili flakes makes it.',
    imageUrl: null,
    ingredients: [
      { name: 'Sourdough bread', quantity: 2, unit: 'slices' },
      { name: 'Avocado', quantity: 1, unit: 'large' },
      { name: 'Eggs', quantity: 2, unit: 'large' },
      { name: 'Lemon juice', quantity: 1, unit: 'tsp' },
      { name: 'Red pepper flakes', quantity: 0.25, unit: 'tsp' },
      { name: 'Salt', quantity: 1, unit: 'pinch' },
      { name: 'Black pepper', quantity: 1, unit: 'pinch' },
      { name: 'Everything bagel seasoning', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Bring a small pot of water to a boil. Gently lower eggs in and cook 7 minutes for soft-boiled. Transfer to an ice bath.',
      'Toast the bread until golden and firm.',
      'Halve and pit the avocado. Scoop flesh into a bowl, add lemon juice, salt, and pepper. Mash to your preferred texture.',
      'Peel the eggs and slice in half.',
      'Spread avocado on toast, top with egg halves, sprinkle with red pepper flakes and everything bagel seasoning.',
    ],
    nutrition: { calories: 340, protein: 14, carbs: 32, fat: 19, fiber: 7 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-2',
    name: 'Classic Spaghetti Bolognese',
    category: 'dinner',
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    notes: 'Low and slow is the key — the longer it simmers, the better. Freeze leftovers flat in zip bags.',
    imageUrl: null,
    ingredients: [
      { name: 'Spaghetti', quantity: 400, unit: 'g' },
      { name: 'Ground beef', quantity: 500, unit: 'g' },
      { name: 'Crushed tomatoes', quantity: 1, unit: 'can (28 oz)' },
      { name: 'Tomato paste', quantity: 2, unit: 'tbsp' },
      { name: 'Yellow onion', quantity: 1, unit: 'medium' },
      { name: 'Garlic', quantity: 4, unit: 'cloves' },
      { name: 'Carrot', quantity: 1, unit: 'medium' },
      { name: 'Celery', quantity: 2, unit: 'stalks' },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'Red wine', quantity: 0.5, unit: 'cup' },
      { name: 'Whole milk', quantity: 0.25, unit: 'cup' },
      { name: 'Parmesan cheese', quantity: 0.5, unit: 'cup' },
      { name: 'Salt and pepper', quantity: 1, unit: 'to taste' },
    ],
    instructions: [
      'Finely dice the onion, carrot, and celery. Mince the garlic.',
      'Heat olive oil in a large heavy pot over medium heat. Cook the soffritto (onion, carrot, celery) for 8–10 minutes until softened.',
      'Add garlic and cook 1 minute more.',
      'Increase heat to medium-high. Add beef and cook, breaking it up, until browned and no pink remains.',
      'Add tomato paste and stir for 2 minutes. Pour in wine and let it reduce by half.',
      'Add crushed tomatoes, reduce heat to low, and simmer uncovered for 30 minutes, stirring occasionally.',
      'Stir in milk and simmer 5 more minutes. Season generously.',
      'Cook spaghetti per package directions. Serve sauce over pasta with parmesan.',
    ],
    nutrition: { calories: 620, protein: 38, carbs: 68, fat: 18, fiber: 5 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-3',
    name: 'Chicken Caesar Salad',
    category: 'lunch',
    servings: 2,
    prepTime: 15,
    cookTime: 12,
    notes: 'The dressing keeps in the fridge for 5 days. Make a double batch.',
    imageUrl: null,
    ingredients: [
      { name: 'Chicken breast', quantity: 2, unit: 'small' },
      { name: 'Romaine lettuce', quantity: 1, unit: 'large head' },
      { name: 'Parmesan cheese', quantity: 0.5, unit: 'cup, shaved' },
      { name: 'Croutons', quantity: 1, unit: 'cup' },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'Mayonnaise', quantity: 3, unit: 'tbsp' },
      { name: 'Lemon juice', quantity: 2, unit: 'tbsp' },
      { name: 'Dijon mustard', quantity: 1, unit: 'tsp' },
      { name: 'Worcestershire sauce', quantity: 1, unit: 'tsp' },
      { name: 'Garlic', quantity: 1, unit: 'clove' },
      { name: 'Salt and pepper', quantity: 1, unit: 'to taste' },
    ],
    instructions: [
      'Season chicken with salt, pepper, and a drizzle of olive oil.',
      'Cook in a skillet over medium-high heat, 5–6 minutes per side, until cooked through. Rest 5 minutes, then slice.',
      'Whisk together mayo, lemon juice, dijon, worcestershire, and grated garlic. Season to taste.',
      'Tear romaine into large pieces. Toss with dressing until well coated.',
      'Top with sliced chicken, croutons, and shaved parmesan. Serve immediately.',
    ],
    nutrition: { calories: 480, protein: 42, carbs: 18, fat: 26, fiber: 3 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-4',
    name: 'Banana Oat Pancakes',
    category: 'breakfast',
    servings: 2,
    prepTime: 5,
    cookTime: 15,
    notes: 'Naturally sweetened — no sugar needed. Great with a drizzle of honey and sliced banana on top.',
    imageUrl: null,
    ingredients: [
      { name: 'Ripe bananas', quantity: 2, unit: 'medium' },
      { name: 'Eggs', quantity: 2, unit: 'large' },
      { name: 'Rolled oats', quantity: 0.5, unit: 'cup' },
      { name: 'Baking powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Cinnamon', quantity: 0.5, unit: 'tsp' },
      { name: 'Vanilla extract', quantity: 1, unit: 'tsp' },
      { name: 'Butter or coconut oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Blend all ingredients (except the cooking fat) until smooth.',
      'Heat a non-stick pan or griddle over medium-low heat and lightly grease.',
      'Pour small rounds (about 3 inches) onto the pan. Cook 2–3 minutes until bubbles form on the surface.',
      'Flip and cook 1–2 minutes more. Repeat with remaining batter.',
      'Serve immediately with maple syrup, fresh fruit, or yogurt.',
    ],
    nutrition: { calories: 290, protein: 11, carbs: 44, fat: 9, fiber: 4 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-5',
    name: 'Garlic Butter Shrimp Stir Fry',
    category: 'dinner',
    servings: 3,
    prepTime: 10,
    cookTime: 10,
    notes: 'Serve over steamed jasmine rice or rice noodles. Don\'t overcook the shrimp — they go from perfect to rubbery fast.',
    imageUrl: null,
    ingredients: [
      { name: 'Large shrimp, peeled and deveined', quantity: 450, unit: 'g' },
      { name: 'Broccoli florets', quantity: 2, unit: 'cups' },
      { name: 'Bell pepper', quantity: 1, unit: 'red' },
      { name: 'Garlic', quantity: 5, unit: 'cloves' },
      { name: 'Butter', quantity: 2, unit: 'tbsp' },
      { name: 'Soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'Honey', quantity: 1, unit: 'tbsp' },
      { name: 'Sesame oil', quantity: 1, unit: 'tsp' },
      { name: 'Red pepper flakes', quantity: 0.5, unit: 'tsp' },
      { name: 'Green onions', quantity: 3, unit: 'stalks' },
      { name: 'Sesame seeds', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Whisk together soy sauce, honey, and sesame oil in a small bowl. Set aside.',
      'Heat butter in a large wok or skillet over high heat until just starting to brown.',
      'Add garlic and red pepper flakes, stir 30 seconds.',
      'Add broccoli and bell pepper. Stir fry 3–4 minutes until just tender.',
      'Push vegetables to the side, add shrimp in a single layer. Cook 1–2 minutes per side.',
      'Pour sauce over everything, toss to coat, and cook 1 minute more.',
      'Garnish with green onions and sesame seeds. Serve over rice.',
    ],
    nutrition: { calories: 310, protein: 34, carbs: 18, fat: 11, fiber: 3 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-6',
    name: 'Tomato Basil Soup',
    category: 'lunch',
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    notes: 'A grilled cheese is mandatory. Use an immersion blender directly in the pot to save dishes.',
    imageUrl: null,
    ingredients: [
      { name: 'Crushed tomatoes', quantity: 2, unit: 'cans (28 oz each)' },
      { name: 'Yellow onion', quantity: 1, unit: 'large' },
      { name: 'Garlic', quantity: 4, unit: 'cloves' },
      { name: 'Vegetable broth', quantity: 2, unit: 'cups' },
      { name: 'Heavy cream', quantity: 0.5, unit: 'cup' },
      { name: 'Butter', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh basil', quantity: 0.5, unit: 'cup' },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'Sugar', quantity: 1, unit: 'tsp' },
      { name: 'Salt and pepper', quantity: 1, unit: 'to taste' },
    ],
    instructions: [
      'Sauté diced onion in butter and olive oil over medium heat until soft, about 8 minutes. Add garlic for 1 minute.',
      'Add crushed tomatoes, broth, and sugar. Bring to a simmer and cook uncovered 20 minutes.',
      'Remove from heat, add basil, and blend until very smooth.',
      'Return to low heat, stir in cream, and season generously.',
      'Serve hot with fresh basil leaves and cracked pepper.',
    ],
    nutrition: { calories: 220, protein: 5, carbs: 24, fat: 13, fiber: 4 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-7',
    name: 'Sheet Pan Chicken Thighs with Roasted Vegetables',
    category: 'dinner',
    servings: 4,
    prepTime: 15,
    cookTime: 40,
    notes: 'Bone-in, skin-on thighs are the move here — more forgiving and way more flavorful. Swap vegetables for whatever needs to be used up.',
    imageUrl: null,
    ingredients: [
      { name: 'Chicken thighs, bone-in skin-on', quantity: 4, unit: 'large' },
      { name: 'Baby potatoes', quantity: 450, unit: 'g' },
      { name: 'Zucchini', quantity: 2, unit: 'medium' },
      { name: 'Cherry tomatoes', quantity: 1, unit: 'cup' },
      { name: 'Red onion', quantity: 1, unit: 'medium' },
      { name: 'Olive oil', quantity: 4, unit: 'tbsp' },
      { name: 'Garlic powder', quantity: 1, unit: 'tsp' },
      { name: 'Paprika', quantity: 1, unit: 'tsp' },
      { name: 'Dried oregano', quantity: 1, unit: 'tsp' },
      { name: 'Salt and pepper', quantity: 1, unit: 'to taste' },
      { name: 'Lemon', quantity: 1, unit: 'sliced' },
    ],
    instructions: [
      'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment.',
      'Halve potatoes and toss with 2 tbsp olive oil, salt, and pepper. Spread on one side of the pan.',
      'Roast potatoes 15 minutes while you prep the chicken.',
      'Pat chicken dry. Rub with remaining olive oil, garlic powder, paprika, oregano, salt, and pepper.',
      'Push potatoes to the edges. Add zucchini chunks, red onion wedges, and tomatoes to the center. Nestle chicken on top, skin side up.',
      'Lay lemon slices around the pan. Roast 25–30 minutes until chicken skin is crispy and cooked through.',
      'Rest 5 minutes before serving.',
    ],
    nutrition: { calories: 540, protein: 38, carbs: 28, fat: 30, fiber: 4 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-8',
    name: 'Greek Yogurt Parfait',
    category: 'snack',
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    notes: 'Layer in a mason jar and refrigerate overnight for a grab-and-go breakfast version.',
    imageUrl: null,
    ingredients: [
      { name: 'Greek yogurt, plain', quantity: 1, unit: 'cup' },
      { name: 'Granola', quantity: 0.5, unit: 'cup' },
      { name: 'Mixed berries', quantity: 0.5, unit: 'cup' },
      { name: 'Honey', quantity: 1, unit: 'tbsp' },
      { name: 'Chia seeds', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Spoon half the yogurt into a glass or bowl.',
      'Add half the granola and half the berries.',
      'Repeat the layers.',
      'Drizzle with honey and sprinkle chia seeds on top.',
    ],
    nutrition: { calories: 380, protein: 22, carbs: 55, fat: 8, fiber: 5 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-9',
    name: 'Garlic Roasted Broccoli',
    category: 'side',
    servings: 4,
    prepTime: 5,
    cookTime: 20,
    notes: 'The slightly charred edges are the whole point — don\'t crowd the pan. A squeeze of lemon at the end is non-negotiable.',
    imageUrl: null,
    ingredients: [
      { name: 'Broccoli', quantity: 1, unit: 'large head' },
      { name: 'Olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'Garlic', quantity: 4, unit: 'cloves' },
      { name: 'Lemon', quantity: 0.5, unit: 'unit' },
      { name: 'Parmesan cheese', quantity: 0.25, unit: 'cup' },
      { name: 'Salt and pepper', quantity: 1, unit: 'to taste' },
      { name: 'Red pepper flakes', quantity: 0.25, unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 450°F (230°C).',
      'Cut broccoli into even florets. Thinly slice the garlic.',
      'Toss broccoli and garlic with olive oil, salt, pepper, and red pepper flakes.',
      'Spread in a single layer on a sheet pan — do not overlap.',
      'Roast 15–18 minutes until edges are well browned.',
      'Squeeze lemon over the top and shower with parmesan. Serve immediately.',
    ],
    nutrition: { calories: 140, protein: 6, carbs: 10, fat: 10, fiber: 4 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-10',
    name: 'Chocolate Chip Cookies',
    category: 'dessert',
    servings: 24,
    prepTime: 15,
    cookTime: 12,
    notes: 'Chill the dough for at least 30 minutes (or overnight) — it makes a huge difference. Pull them out when they still look slightly underdone.',
    imageUrl: null,
    ingredients: [
      { name: 'All-purpose flour', quantity: 2.25, unit: 'cups' },
      { name: 'Butter, softened', quantity: 1, unit: 'cup (2 sticks)' },
      { name: 'Brown sugar', quantity: 0.75, unit: 'cup, packed' },
      { name: 'White sugar', quantity: 0.75, unit: 'cup' },
      { name: 'Eggs', quantity: 2, unit: 'large' },
      { name: 'Vanilla extract', quantity: 2, unit: 'tsp' },
      { name: 'Baking soda', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 1, unit: 'tsp' },
      { name: 'Chocolate chips', quantity: 2, unit: 'cups' },
    ],
    instructions: [
      'Whisk together flour, baking soda, and salt in a bowl. Set aside.',
      'Beat butter and both sugars together until light and fluffy, about 3 minutes.',
      'Beat in eggs one at a time, then vanilla.',
      'Gradually add flour mixture, mixing just until combined. Fold in chocolate chips.',
      'Chill dough at least 30 minutes.',
      'Preheat oven to 375°F (190°C). Line baking sheets with parchment.',
      'Scoop dough into balls (about 2 tbsp each) onto prepared sheets, spacing 2 inches apart.',
      'Bake 10–12 minutes until edges are set but centers still look slightly underdone.',
      'Cool on the pan 5 minutes before transferring.',
    ],
    nutrition: { calories: 210, protein: 2, carbs: 28, fat: 10, fiber: 1 },
    createdAt: new Date().toISOString(),
  },
]

export async function seedIfEmpty(userId) {
  if (!userId) return

  const { data: existing } = await supabase
    .from('recipes')
    .select('id')
    .eq('user_id', userId)
    .limit(1)

  if (existing && existing.length > 0) return

  const rows = SEED_RECIPES.map(({ id, createdAt, imageUrl, prepTime, cookTime, ...r }) => ({
    ...r,
    user_id:   userId,
    prep_time: prepTime,
    cook_time: cookTime,
    image_url: imageUrl ?? null,
  }))

  await supabase.from('recipes').insert(rows)
}
