const ABBR = {
  'tablespoon':    'tbsp',
  'tablespoons':   'tbsp',
  'tbsp':          'tbsp',
  'teaspoon':      'tsp',
  'teaspoons':     'tsp',
  'tsp':           'tsp',
  'pound':         'lb',
  'pounds':        'lb',
  'ounce':         'oz',
  'ounces':        'oz',
  'fluid ounce':   'fl oz',
  'fluid ounces':  'fl oz',
  'cup':           'cup',
  'cups':          'cups',
  'liter':         'L',
  'liters':        'L',
  'litre':         'L',
  'litres':        'L',
  'milliliter':    'ml',
  'milliliters':   'ml',
  'millilitre':    'ml',
  'millilitres':   'ml',
  'gram':          'g',
  'grams':         'g',
  'kilogram':      'kg',
  'kilograms':     'kg',
  'medium':        'med.',
  'large':         'lg.',
  'small':         'sm.',
  'package':       'pkg',
  'packages':      'pkg',
  'packet':        'pkt',
  'packets':       'pkt',
  'inch':          'in',
  'inches':        'in',
  'pinch':         'pinch',
  'handful':       'hndf',
  'clove':         'clove',
  'cloves':        'cloves',
  'slice':         'slice',
  'slices':        'slices',
  'piece':         'pc',
  'pieces':        'pcs',
  'can':           'can',
  'cans':          'cans',
  'jar':           'jar',
  'jars':          'jars',
  'bag':           'bag',
  'bags':          'bags',
  'bunch':         'bunch',
  'head':          'head',
  'stalk':         'stalk',
  'stalks':        'stalks',
  'sprig':         'sprig',
  'sprigs':        'sprigs',
  'quart':         'qt',
  'quarts':        'qt',
  'gallon':        'gal',
  'gallons':       'gal',
  'pint':          'pt',
  'pints':         'pt',
}

export function abbreviateUnit(unit) {
  if (!unit) return ''
  const lower = unit.trim().toLowerCase()
  return ABBR[lower] ?? unit
}
